In [ ]:
import numpy as np
from functools import reduce

a = [1.0, 2.0, 1.5, 3.5, 0.5, 2.1, 1.3, 4.5,-1.0, 1.0, 2.0, 3.0, 1.5, 2.6, 3.5, 0.6]
print(list(map(lambda x: x**2, a)))
print(reduce(lambda x, y: x+y, map(lambda x: x**2, a)))


b = np.array([-1.0, 1.0, 2.0, 3.0]).reshape((4, 1))
w = np.array([1.0, 2.0, 1.5, 3.5, 0.5, 2.1, 1.3, 4.5]).reshape((4, 2))
v = np.array([1.5, 2.6, 3.5, 0.6]).reshape((4,1))
x = np.array([2.5, -1.5, 3.6, 1.3, -1.5, 2.0]).reshape((3,2))
y = np.array([9.1, 3.2, 6.3]).reshape((3,1))
print(b)
print(w)
print(v)
print(x)
print(x[0, 0], x[1])

[1.0, 4.0, 2.25, 12.25, 0.25, 4.41, 1.6900000000000002, 20.25, 1.0, 1.0, 4.0, 9.0, 2.25, 6.760000000000001, 12.25, 0.36]
82.72
[[-1.]
 [ 1.]
 [ 2.]
 [ 3.]]
[[ 1.   2. ]
 [ 1.5  3.5]
 [ 0.5  2.1]
 [ 1.3  4.5]]
[[ 1.5]
 [ 2.6]
 [ 3.5]
 [ 0.6]]
[[ 2.5 -1.5]
 [ 3.6  1.3]
 [-1.5  2. ]]
2.5 [ 3.6  1.3]


In [7]:
np.tanh(1.0)

0.76159415595576485

In [2]:
def g(t):
    return np.tanh(t/2)

N = 4
n = 2
P = 3

result = 0

for k in range(P):
    print("##")
    all_sum = 0
    for j in range(N):
        m_sum = 0
        for i in range(n):
            print(w[j,i],"*",x[k, i])
            m_sum += w[j, i]*x[k, i]
        print("g(",m_sum,"-", b[j, 0],")")
        m_sum = g(m_sum-b[j, 0])
        print(v[j,0],"* g ",m_sum)
        all_sum += v[j, 0]*m_sum
    print("f(x{})=".format(k), all_sum)
    print(all_sum,"-", y[k, 0], "=", all_sum-y[k, 0])
    value = (all_sum-y[k, 0])**2
    print(all_sum,"-", y[k, 0], "=", value)
    result += value

print((1.0/(2.0*P)*result))
    
    
all_sum

y = 9.1

##
1.0 * 2.5
2.0 * -1.5
g( -0.5 - -1.0 )
1.5 * g  0.244918662404
1.5 * 2.5
3.5 * -1.5
g( -1.5 - 1.0 )
2.6 * g  -0.848283639958
0.5 * 2.5
2.1 * -1.5
g( -1.9 - 2.0 )
3.5 * g  -0.960319388532
1.3 * 2.5
4.5 * -1.5
g( -3.5 - 3.0 )
0.6 * g  -0.996997635487
f(x0)= -5.79747591144
-5.79747591144 - 9.1 = -14.8974759114
-5.79747591144 - 9.1 = 221.934788532
##
1.0 * 3.6
2.0 * 1.3
g( 6.2 - -1.0 )
1.5 * g  0.998507942332
1.5 * 3.6
3.5 * 1.3
g( 9.95 - 1.0 )
2.6 * g  0.999740559339
0.5 * 3.6
2.1 * 1.3
g( 4.53 - 2.0 )
3.5 * g  0.852436706795
1.3 * 3.6
4.5 * 1.3
g( 10.53 - 3.0 )
0.6 * g  0.998927099353
f(x1)= 7.67997210117
7.67997210117 - 3.2 = 4.47997210117
7.67997210117 - 3.2 = 20.0701500273
##
1.0 * -1.5
2.0 * 2.0
g( 2.5 - -1.0 )
1.5 * g  0.941375538497
1.5 * -1.5
3.5 * 2.0
g( 4.75 - 1.0 )
2.6 * g  0.95404526018
0.5 * -1.5
2.1 * 2.0
g( 3.45 - 2.0 )
3.5 * g  0.619996867969
1.3 * -1.5
4.5 * 2.0
g( 7.05 - 3.0 )
0.6 * g  0.965751933369
f(x2)= 6.64202118213
6.64202118213 - 6.3 = 0.342021182128
6.642021182

In [3]:
import tensorflow as tf

b = tf.constant([-1.0, 1.0, 2.0, 3.0], shape=[4, 1])
w = tf.constant([1.0, 2.0, 1.5, 3.5, 0.5, 2.1, 1.3, 4.5], shape=[4, 2])
v = tf.constant([1.5, 2.6, 3.5, 0.6], shape=[4, 1])
x = tf.constant([2.5, -1.5, 3.6, 1.3, -1.5, 2.0], shape=[3, 2])
y = tf.constant([9.1, 3.2, 6.3], shape=[3,1])

mm = tf.tanh(tf.subtract(tf.matmul(x, w, transpose_b=True), tf.transpose(b))/2.0)
f = tf.matmul(tf.transpose(v),tf.transpose(mm))
s_d = tf.squared_difference(f, tf.transpose(y))
r_m = tf.reduce_mean(s_d)/2.0

with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(mm))
    print(sess.run(f))
    print(sess.run(y))
    print(sess.run(f))
    print(sess.run(tf.transpose(y)))
    print(sess.run(s_d))
    print(sess.run(r_m))

[[ 2.5        -1.5       ]
 [ 3.5999999   1.29999995]
 [-1.5         2.        ]]
[[ 0.24491866 -0.84828371 -0.96031934 -0.99699771]
 [ 0.99850798  0.99974054  0.85243672  0.99892718]
 [ 0.94137555  0.95404524  0.61999685  0.96575201]]
[[-5.79747581  7.67997217  6.6420207 ]]
[[ 9.10000038]
 [ 3.20000005]
 [ 6.30000019]]
[[-5.79747581  7.67997217  6.6420207 ]]
[[ 9.10000038  3.20000005  6.30000019]]
[[  2.21934799e+02   2.00701485e+01   1.16978027e-01]]
40.3537


In [23]:
def tprint(x, sess):
    print(sess.run(x))

In [56]:
import tensorflow as tf

# TODO: Change dimensions

b = tf.constant([-1.0, 1.0, 2.0, 3.0], shape=[4, 1])
w = tf.constant([1.0, 2.0, 1.5, 3.5, 0.5, 2.1, 1.3, 4.5], shape=[4, 2])
v = tf.constant([1.5, 2.6, 3.5, 0.6], shape=[4, 1])
x = tf.constant([2.5, -1.5, 3.6, 1.3, -1.5, 2.0], shape=[3, 2])
print(x)
y = tf.constant([9.1, 3.2, 6.3], shape=[3,1])
rho = tf.constant(0.01)

#con = tf.concat([tf.reshape(w, [-1]), tf.reshape(b, [-1]), tf.reshape(v, [-1])], 0)
con = tf.concat([w, b, v], 1)

#regularization = rho*tf.square(tf.norm(tf.concat([tf.reshape(w, [-1]), tf.reshape(b, [-1]), tf.reshape(v, [-1])], 0)))
regularization = rho*tf.reduce_sum(tf.square(con))

mm = tf.tanh(tf.subtract(tf.matmul(x, w, transpose_b=True), tf.transpose(b))/2.0)
f = tf.matmul(tf.transpose(v), tf.transpose(mm))
mse = tf.losses.mean_squared_error(labels=y, predictions=tf.transpose(f))
loss = mse + regularization
s_d = tf.squared_difference(f, tf.transpose(y))
r_m = tf.reduce_mean(s_d)/2.0


with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(con))
    print(sess.run(con2))
    '''
    print(sess.run(norm))
    print(sess.run(x))
    print(sess.run(mm))
    print(sess.run(f))
    print(sess.run(y))
    print(sess.run(f))
    print(sess.run(tf.transpose(y)))
    print(sess.run(s_d))
    '''
    tprint(f, sess)
    tprint(mm, sess)
    print(sess.run(f))
    print(sess.run(y))
    print(sess.run(mse))
    print(sess.run(r_m))
    tprint(regularization, sess)
    tprint(loss, sess)

Tensor("Const_315:0", shape=(3, 2), dtype=float32)
[[ 2.5        -1.5       ]
 [ 3.5999999   1.29999995]
 [-1.5         2.        ]]
[[ 1.          2.         -1.          1.5       ]
 [ 1.5         3.5         1.          2.5999999 ]
 [ 0.5         2.0999999   2.          3.5       ]
 [ 1.29999995  4.5         3.          0.60000002]]
[[ 1.          2.         -1.          1.5       ]
 [ 1.5         3.5         1.          2.5999999 ]
 [ 0.5         2.0999999   2.          3.5       ]
 [ 1.29999995  4.5         3.          0.60000002]]
[[-5.79747581  7.67997217  6.6420207 ]]
[[ 0.24491866 -0.84828371 -0.96031934 -0.99699771]
 [ 0.99850798  0.99974054  0.85243672  0.99892718]
 [ 0.94137555  0.95404524  0.61999685  0.96575201]]
[[-5.79747581  7.67997217  6.6420207 ]]
[[ 9.10000038]
 [ 3.20000005]
 [ 6.30000019]]
80.7073
40.3537
0.8272
81.5345


In [60]:
import tensorflow as tf

# TODO: Change dimensions

b = tf.constant([-1.0, 1.0, 2.0, 3.0], shape=[4, 1])
w = tf.constant([1.0, 2.0, 1.5, 3.5, 0.5, 2.1, 1.3, 4.5], shape=[4, 2])
v = tf.constant([1.5, 2.6, 3.5, 0.6], shape=[4, 1])
rho = tf.constant(0.01)

x = tf.placeholder(tf.float32, shape = [3,2])
y = tf.placeholder(tf.float32, shape = [3,1])

con = tf.concat([w, b, v], 1)
regularization = rho*tf.reduce_sum(tf.square(con))
mm = tf.tanh(tf.subtract(tf.matmul(x, w, transpose_b=True), tf.transpose(b))/2.0)
f = tf.matmul(tf.transpose(v), tf.transpose(mm))
mse = tf.losses.mean_squared_error(labels=y, predictions=tf.transpose(f))/2.0
loss = mse + regularization
#s_d = tf.squared_difference(f, tf.transpose(y))
#r_m = tf.reduce_mean(s_d)/2.0

train_x = np.array([2.5, -1.5, 3.6, 1.3, -1.5, 2.0], dtype=np.float32).reshape((3,2))
print(train_x.shape)
print(train_x)
train_y = np.array([9.1, 3.2, 6.3], dtype=np.float32).reshape(3,1)

with tf.Session() as sess:
    a=sess.run([loss], feed_dict = {x: train_x, y: train_y})
    print(a[0])
    '''
    print(sess.run(norm))
    print(sess.run(x))
    print(sess.run(mm))
    print(sess.run(f))
    print(sess.run(y))
    print(sess.run(f))
    print(sess.run(tf.transpose(y)))
    print(sess.run(s_d))
    '''

(3, 2)
[[ 2.5        -1.5       ]
 [ 3.5999999   1.29999995]
 [-1.5         2.        ]]
41.1809


In [ ]:
3.75-5.25

In [32]:
2.5*0.5-1.5*2.1

-1.9000000000000004

In [33]:
2.5*1.3-1.5*4.5

-3.5